### ISSUE TITLE
[el-dialog] [Attribute] custom-class is about to be deprecated in version 2.3.0, please use class instead

### ISSUE THREAD

**Issue by Aurorxa** [caroundsky/el-plus-dialog-service#2]
error.ts:14 ElementPlusError: [el-dialog] [Attribute] custom-class is about to be deprecated in version 2.3.0, please use class instead.
For more detail, please visit: https://element-plus.org/en-US/component/dialog.html#attributes

    at debugWarn (error.ts:13:37)
    at watch.immediate (index.ts:6:7)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at job (runtime-core.esm-bundler.js:1774:17)
    at doWatch (runtime-core.esm-bundler.js:1813:13)
    at watch (runtime-core.esm-bundler.js:1660:12)
    at useDeprecated (index.ts:4:3)
    at setup (dialog.vue:103:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)

**Comment by Aurorxa** [comment]
element-plus 报 custom-class 已经被弃用了，能否修复一下，谢谢

**Comment by caroundsky** [comment]
已在0.4版本修改，升级依赖即可。

上回关闭的问题中，我看到截图内有 `onClick: async ({vm, ctx, component}: DialogConfig)`，`DialogConfig`类型应该会自动推断出来，无需手动指定的

**Comment by Aurorxa** [comment]
> 已在0.4版本修改，升级依赖即可。
> 
> 上回关闭的问题中，我看到截图内有 `onClick: async ({vm, ctx, component}: DialogConfig)`，`DialogConfig`类型应该会自动推断出来，无需手动指定的

哈哈，我也不是很清楚，感觉 Vue 和 TS 结合，感觉很奇怪，我是前端新手，一直写 Java ，谢谢！！
